drivers: Add Home Assistant driver
pdudaemon/pdudaemon pull request #159
Opened 2024-05-26 12:19 UTC by fooishbar

Add a very simple driver which allows using the Home Assistant switch API to bridge to e.g. Zigbee devices.

2024-05-27 07:23 UTC, jluebbe requested changes
Looks good otherwise.

2024-05-27 07:23 UTC, jluebbe commented on pdudaemon/drivers/homeassistant.py
> +        """
Please update this comment.

2024-05-28 16:04 UTC, fooishbar commented
@jluebbe done now, thanks a lot

2024-06-02 12:11 UTC, fooishbar commented
Pushed a simple change to allow using the `hostname` config variable to override this.

2024-06-03 09:21 UTC, Emantor approved these changes

2024-07-02 12:29 UTC, jluebbe approved these changes

2024-07-02 12:30 UTC, merged